spring:
  profiles:
    active: @activatedProperties@
  application:
      name: point
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant-path-matcher
  #    freemarker静态资源配置
  freemarker:
    template-loader-path: classpath*:/templates/
#    关闭缓存，及时刷新，上线生产环境需要修改为true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html
# 数据库连接信息 JDBC url
  datasource:
    url: jdbc:sqlite:jsls-server/data/sqlite/test.db
    # 数据库驱动名称
    driverClassName: org.sqlite.JDBC
    # 数据库用户名
    username: 
    # 数据库密码
    password: 
# Dialect
  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false